defmodule Ryker.Work.FinalPreflightTest do
  use Ryker.DataCase, async: true

  alias Ryker.Work.FinalPreflight

  test "host-issued output artifact identities do not spend a second final preflight" do
    # Coop can name generated bytes only after the model returns. Requiring the
    # exact late-issued ID made an image journey spend all three semantic
    # repairs: preflight, artifact-ID repair, then preflight again.
    before_host_identity = candidate(["generated-1.png"])
    after_host_identity = candidate(["artifact_7aabc324e6e07625e2af06a3"])

    assert FinalPreflight.candidate_sha256(before_host_identity) ==
             FinalPreflight.candidate_sha256(after_host_identity)

    refute FinalPreflight.candidate_sha256(before_host_identity) ==
             FinalPreflight.candidate_sha256(%{
               after_host_identity
               | "message" => "A different visible answer."
             })

    episode_id = Ecto.UUID.generate()

    assert FinalPreflight.ledger_sha256(episode_id, 1, ["generated-1.png"]) ==
             FinalPreflight.ledger_sha256(episode_id, 1, [
               "artifact_7aabc324e6e07625e2af06a3"
             ])
  end

  defp candidate(artifact_refs) do
    %{
      "decision_reason" => nil,
      "delivery" => "reply",
      "message" => "Attached is a compact handoff chart.",
      "outcome" => %{
        "artifact_refs" => artifact_refs,
        "record_refs" => [],
        "state" => "complete"
      }
    }
  end
end
